### ISSUE TITLE
broker/httpd test is flaky

### ISSUE THREAD

**Issue by paulhuggett** [SNSystems/pstore#82]
I'm seeing intermittent failures of the broker/httpd test on slow machines. Here is the log ([original](https://pipelines.actions.githubusercontent.com/aSkMCuFMe8QFZmxv3IDPV8PBp2OApeQzyKQ1M7ybvY6Il4M8FG/_apis/pipelines/1/runs/21/signedlogcontent/9?urlExpires=2021-01-06T13%3A33%3A28.8864310Z&urlSigningMethod=HMACV1&urlSignature=N2GTxidnEEKIrHoF66qETV%2FZ38H4lUuL%2F0%2F%2FnNkzN4I%3D)) from a CI Windows-latest/MSVC/Debug build:

~~~
2021-01-05T16:54:41.8332470Z   FAIL: pstore :: broker/httpd.test (5 of 22)
2021-01-05T16:54:41.8376768Z   ******************** TEST 'pstore :: broker/httpd.test' FAILED ********************
2021-01-05T16:54:41.8425076Z   Script:
2021-01-05T16:54:41.8508657Z   --
2021-01-05T16:54:41.8514490Z   : 'RUN: at line 8';   C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe "D:\a\pstore\pstore\system_tests\broker/httpd.py" "D:/a/pstore/build/bin/Debug" > "D:\a\pstore\build\bin\Debug\system_tests\broker\Output\httpd.test.tmp"
2021-01-05T16:54:41.8517974Z   --
2021-01-05T16:54:41.8526467Z   Exit Code: 1
2021-01-05T16:54:41.8594588Z   
2021-01-05T16:54:41.8600056Z   Command Output (stdout):
2021-01-05T16:54:41.8622601Z   --
2021-01-05T16:54:41.8665450Z   $ ":" "RUN: at line 8"
2021-01-05T16:54:41.8841020Z   $ "C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe" "D:\a\pstore\pstore\system_tests\broker/httpd.py" "D:/a/pstore/build/bin/Debug"
2021-01-05T16:54:41.8844667Z   # command stderr:
2021-01-05T16:54:41.8848141Z   2021-01-05T16:54:36+0000 - main - notice - broker starting
2021-01-05T16:54:41.8856030Z   
2021-01-05T16:54:41.8857477Z   2021-01-05T16:54:36+0000 - main - notice - opening pipe
2021-01-05T16:54:41.8858179Z   
2021-01-05T16:54:41.8858910Z   2021-01-05T16:54:36+0000 - main - notice - starting threads
2021-01-05T16:54:41.8859553Z   
2021-01-05T16:54:41.8860227Z   2021-01-05T16:54:36+0000 - main - notice - waiting
2021-01-05T16:54:41.8860821Z   
2021-01-05T16:54:41.8861554Z   2021-01-05T16:54:36+0000 - command - info - Waiting for commands
2021-01-05T16:54:41.8862270Z   
2021-01-05T16:54:41.8863108Z   2021-01-05T16:54:36+0000 - gcwatch - info - starting gc process watch thread
2021-01-05T16:54:41.8863804Z   
2021-01-05T16:54:41.8864614Z   2021-01-05T16:54:36+0000 - gcwatch - info - waiting for a GC process to complete
2021-01-05T16:54:41.8865601Z   
2021-01-05T16:54:41.8866360Z   2021-01-05T16:54:36+0000 - http - info - initializing on port: 49875
2021-01-05T16:54:41.8867102Z   
2021-01-05T16:54:41.8867868Z   2021-01-05T16:54:36+0000 - uptime - info - uptime 1 second tick starting
2021-01-05T16:54:41.8868538Z   
2021-01-05T16:54:41.8869418Z   2021-01-05T16:54:36+0000 - read0 - notice - listening to named pipe "\\.\pipe\httpd.py"
2021-01-05T16:54:41.8870140Z   
2021-01-05T16:54:41.8872042Z   2021-01-05T16:54:36+0000 - read1 - notice - listening to named pipe "\\.\pipe\httpd.py"
2021-01-05T16:54:41.8872994Z   
2021-01-05T16:54:41.8874448Z   2021-01-05T16:54:36+0000 - http - error - opening socketAn attempt was made to access a socket in a way forbidden by its access permissions.
2021-01-05T16:54:41.8875485Z   
2021-01-05T16:54:41.8876307Z   2021-01-05T16:54:40+0000 - quit - info - Signal received: shutting down. Signal: SIGBREAK
2021-01-05T16:54:41.8877081Z   
2021-01-05T16:54:41.8877683Z   pstore broker is exiting.
2021-01-05T16:54:41.8878252Z   
2021-01-05T16:54:41.8879219Z   2021-01-05T16:54:40+0000 - quit - info - performing shutdown
2021-01-05T16:54:41.8879922Z   
2021-01-05T16:54:41.8880869Z   2021-01-05T16:54:40+0000 - quit - info - asking gc process watch thread to exit
2021-01-05T16:54:41.8882043Z   
2021-01-05T16:54:41.8882704Z   2021-01-05T16:54:40+0000 - quit - info - push command "_QUIT"
2021-01-05T16:54:41.8883327Z   
2021-01-05T16:54:41.8883973Z   2021-01-05T16:54:40+0000 - gcwatch - info - cleaning up
2021-01-05T16:54:41.8884797Z   
2021-01-05T16:54:41.8885625Z   2021-01-05T16:54:40+0000 - quit - info - push command "_QUIT"
2021-01-05T16:54:41.8886267Z   
2021-01-05T16:54:41.8886986Z   2021-01-05T16:54:40+0000 - quit - info - push command "_CQUIT"
2021-01-05T16:54:41.8887628Z   
2021-01-05T16:54:41.8888314Z   2021-01-05T16:54:40+0000 - scavenger - info - begin scavenging
2021-01-05T16:54:41.8889153Z   
2021-01-05T16:54:41.8889897Z   2021-01-05T16:54:40+0000 - scavenger - info - scavenger thread exiting
2021-01-05T16:54:41.8890614Z   
2021-01-05T16:54:41.8898061Z   2021-01-05T16:54:40+0000 - command - info - verb:_QUIT path:
2021-01-05T16:54:41.8898894Z   
2021-01-05T16:54:41.8899590Z   2021-01-05T16:54:40+0000 - command - info - waking one reader thread
2021-01-05T16:54:41.8900244Z   
2021-01-05T16:54:41.8900941Z   2021-01-05T16:54:40+0000 - quit - info - shutdown requests complete
2021-01-05T16:54:41.8901598Z   
2021-01-05T16:54:41.8902253Z   2021-01-05T16:54:40+0000 - quit - info - quit thread exiting
2021-01-05T16:54:41.8902866Z   
2021-01-05T16:54:41.8903514Z   2021-01-05T16:54:40+0000 - command - info - verb:_QUIT path:
2021-01-05T16:54:41.8904128Z   
2021-01-05T16:54:41.8904790Z   2021-01-05T16:54:40+0000 - read0 - notice - exiting read loop
2021-01-05T16:54:41.8906204Z   
2021-01-05T16:54:41.8907069Z   2021-01-05T16:54:40+0000 - command - info - waking one reader thread
2021-01-05T16:54:41.8909208Z   
2021-01-05T16:54:41.8910861Z   2021-01-05T16:54:40+0000 - read1 - notice - exiting read loop
2021-01-05T16:54:41.8912591Z   
2021-01-05T16:54:41.8913598Z   2021-01-05T16:54:40+0000 - command - info - verb:_CQUIT path:
2021-01-05T16:54:41.8914319Z   
2021-01-05T16:54:41.8915193Z   2021-01-05T16:54:40+0000 - command - info - Exiting command thread
2021-01-05T16:54:41.8916077Z   
2021-01-05T16:54:41.8916800Z   2021-01-05T16:54:41+0000 - uptime - info - uptime thread exiting
2021-01-05T16:54:41.8917463Z   
2021-01-05T16:54:41.8918224Z   2021-01-05T16:54:41+0000 - main - notice - worker threads done: stopping quit thread
2021-01-05T16:54:41.8918927Z   
2021-01-05T16:54:41.8919535Z   2021-01-05T16:54:41+0000 - main - notice - exiting
2021-01-05T16:54:41.8920125Z   
2021-01-05T16:54:41.8920660Z   Using HTTP port 49875
2021-01-05T16:54:41.8921207Z   
2021-01-05T16:54:41.8921986Z   broker args: ['--pipe-path', '\\\\.\\pipe\\httpd.py', '--http-port', '49875']
2021-01-05T16:54:41.8922711Z   
2021-01-05T16:54:41.8923234Z   Broker alive.
2021-01-05T16:54:41.8923988Z   
2021-01-05T16:54:41.8924617Z   Connecting to broker at localhost:49875
2021-01-05T16:54:41.8925231Z   
2021-01-05T16:54:41.8925868Z   Sent SIGTERM. Waiting for broker to exit.
2021-01-05T16:54:41.8926490Z   
2021-01-05T16:54:41.8927125Z   Broker exited. Done.
2021-01-05T16:54:41.8927684Z   
2021-01-05T16:54:41.8928285Z   Traceback (most recent call last):
2021-01-05T16:54:41.8928898Z   
2021-01-05T16:54:41.8929699Z     File "D:\a\pstore\pstore\system_tests\broker/httpd.py", line 193, in <module>
2021-01-05T16:54:41.8930434Z   
2021-01-05T16:54:41.8931219Z       timeout=args.timeout))
2021-01-05T16:54:41.8931754Z   
2021-01-05T16:54:41.8932524Z     File "D:\a\pstore\pstore\system_tests\broker/httpd.py", line 174, in main
2021-01-05T16:54:41.8933192Z   
2021-01-05T16:54:41.8934078Z       reply = http_get(host, port).decode("utf-8")
2021-01-05T16:54:41.8935054Z   
2021-01-05T16:54:41.8935866Z     File "D:\a\pstore\pstore\system_tests\broker/httpd.py", line 154, in http_get
2021-01-05T16:54:41.8937019Z   
2021-01-05T16:54:41.8937797Z       conn.connect()
2021-01-05T16:54:41.8938255Z   
2021-01-05T16:54:41.8939243Z     File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\http\client.py", line 944, in connect
2021-01-05T16:54:41.8940101Z   
2021-01-05T16:54:41.8940993Z       (self.host,self.port), self.timeout, self.source_address)
2021-01-05T16:54:41.8941814Z   
2021-01-05T16:54:41.8942886Z     File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\socket.py", line 728, in create_connection
2021-01-05T16:54:41.8943605Z   
2021-01-05T16:54:41.8944219Z       raise err
2021-01-05T16:54:41.8944639Z   
2021-01-05T16:54:41.8945445Z     File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\socket.py", line 716, in create_connection
2021-01-05T16:54:41.8946185Z   
2021-01-05T16:54:41.8946711Z       sock.connect(sa)
2021-01-05T16:54:41.8947212Z   
2021-01-05T16:54:41.8950554Z   ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2021-01-05T16:54:41.8952002Z   
2021-01-05T16:54:41.8952454Z   
2021-01-05T16:54:41.8953612Z CUSTOMBUILD : error : command failed with exit status: 1 [D:\a\pstore\build\pstore-system-tests.vcxproj]
2021-01-05T16:54:41.8954721Z   
2021-01-05T16:54:41.8955318Z   --
2021-01-05T16:54:41.8955698Z   
~~~

Note the line which says:
~~~
http - error - opening socketAn attempt was made to access a socket in a way forbidden by its access permissions.
~~~
This may originate from the hard-wired ephemeral port number in the httpd.py test which could collide with pre-existing use of that port on the machine.

**Comment by paulhuggett** [comment]
A second potential cause of intermittent failure could be the use of a fixed-duration sleep in the httpd python test code:

~~~python
    # TODO: this is a crude way to wait for the broker to be fully up: we don't know how long the
    # system will take to start the process before it actually gets to do any work.
    time.sleep(2)  # Wait until the broker is alive.
~~~

This can be resolved by having the broker emit some test to stdout when it is initialized and listening. The python code can then wait until it sees this text (or a timeout expires). 

If the HTTP library is extended to allow 0 to be passed to the broker as the HTTP listen port causing the system to choose a free ephemeral port number. The selected port number can then be displayed allowing both problems to be avoided.

**Comment by paulhuggett** [comment]
Closing in the expectation that commit 00183671da8d1a933218985c5495b090c7f3ebf4 will have fixed this problem once and for all.
